### ISSUE TITLE
Allow publication of null payloads

### ISSUE THREAD

**Issue by caspiano** [spider-gazelle/crystal-mqtt#1]
MQTT allows publication of `null` payloads to topics.
This is useful for clearing retained messages in a topic.

**Comment by stakach** [comment]
This is already supported
`client.publish("topic/with/no/payload")`
OR
`client.publish("topic/with/no/payload", "")`

unless I'm missing something?

**Comment by stakach** [comment]
Currently the code looks like

```crystal
      def payload=(message)
        @payload = message.to_slice
      end
```

We could explicitly allow passing of `nil`

```crystal
      def payload=(message)
        if message
            @payload = message.to_slice
        else
            @payload = Bytes.new(0)
        end
      end
```
