### ISSUE TITLE
IO Error Broken pipe when waiting for subscribed messages

### ISSUE THREAD

**Issue by repomaa** [spider-gazelle/crystal-mqtt#4]
I noticed that the client will stop receiving messages at some point. If ping is then sent, it will fail with an IO Error (Broken Pipe)

**Comment by repomaa** [comment]
Here's how it looks like:

```
Unhandled exception: IO error (MQTT::Error)
  from api/lib/promise/src/promise/deferred_promise.cr:120:5 in 'get'
  from usr/share/crystal/src/concurrent.cr:14:3 in 'subscribe'
  from usr/share/crystal/src/hash.cr:896:11 in 'cli'
  from api/src/main.cr:96:1 in '__crystal_main'
  from usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

The broken pipe i got when i had a ping running in a spawned endless loop:

```
Unhandled exception in spawn: IO error (MQTT::Error)
  from api/lib/promise/src/promise/deferred_promise.cr:120:5 in 'get'
  from usr/share/crystal/src/concurrent.cr:14:3 in '->'
  from usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
Caused by: Error writing to socket: Broken pipe (IO::Error)
  from usr/share/crystal/src/io/evented.cr:156:7 in 'unbuffered_write'
  from usr/share/crystal/src/io/buffered.cr:217:5 in 'process_requests!'
  from usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
```

**Comment by stakach** [comment]
Thanks for pointing that out.

I've noticed that, on many corporate networks, TCP connections are silently dropped after an idle period and the only way your local machine can detect the disconnect is by sending traffic.

We typically send a ping every 50seconds to maintain the connection - but I've seen networks that drop connections with idle times as low as 30 seconds.

The latest patch should allow reconnect behaviour to trigger if the connection is dropped, detected by a failed send
definitely recommend a regular ping to maintain the connection and detect disconnects too
