### ISSUE TITLE
Add read_timeout to TCPSocket?

### ISSUE THREAD

**Issue by atlantis** [spider-gazelle/crystal-mqtt#8]
I'm hitting a very, very rare case in production where occasionally MQTT hangs indefinitely - this corresponds to network/DNS resolution blips, and unfortunately I have no way to consistently replicate it :( 

However, i'm wondering from https://github.com/crystal-lang/crystal/issues/8108 if perhaps setting a reasonable read_timeout on the TCPSocket would prevent this from happening?

**Comment by stakach** [comment]
Yeah probably a good idea

**Comment by stakach** [comment]
actually looking at the code it doesn't make sense as it might be a long time until the next message is sent.
we've not sent anything to expect a response - could come at any time.

I think what needs to happen is that in your code you need to periodically send messages. Something that won't break your application and otherwise has no effect. This tests the connection and allows the OS to decide if the connection has broken

**Comment by stakach** [comment]
that's the annoying thing about TCP it's not broken until a transmission has failed

**Comment by atlantis** [comment]
Hmmm yes but I have something like that and the odd thing is that the freeze happens inside my reconnect loop! So inside my reconnect code I:

1. log that I'm about to connect (this prints fine)
2. create a new transport with TLS 
3. create a ::MQTT::V3::Client with said transport
4. call `connect()` on said client
5. call `ping()` on client
6. publish a message letting the backend know we've connected
7. sleep 6 seconds to avoid subscription race condition 
8. log a message that I'm about to subscribe to topics <- this log message never happens!

So between the ping and the publish I'd very much expect an error to be thrown (I'm also using a keep_alive in connect)... but somehow the whole thing just hangs forever unfortunately...

**Comment by stakach** [comment]
Would you be happy to share the code?
Just so it's easier to understand the problem

**Comment by atlantis** [comment]
Sorry for the delay - I just spent several days replicating/debugging this and wanted to update this issue as a signpost for future Crystal developers.

Short story: your MQTT library is not to blame, even though the line that was freezing my entire program was:

`::MQTT::Transport::TCP.new(uri.host.not_nil!, uri.port.not_nil!)`

The culprit was actually #*@#(#@#  `LibC.getaddrinfo`! As described https://forum.crystal-lang.org/t/400-cpu-usage-at-idle-thread-new-plus-channel-receive/5423 and https://github.com/crystal-lang/crystal/issues/8376 it blocks the main thread and hence your entire Crystal program hangs until it decides to timeout.

Be warned if you're using any crystal libraries that resolve DNS!

**Comment by stakach** [comment]
always wondered why Libuv ran getaddrinfo in the thread pool
all makes sense now - seems like a poor design decision on Linux's part but hopefully solved in crystal soon
